spring.application.name=flousi-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/flousi_db
spring.datasource.username=flousi
spring.datasource.password=flousi_password

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true

server.port=8080